# 指定node版本
FROM node:8

# Create app directory
WORKDIR /message-api 

# 將檔案複製到上一行產生的資料夾
ADD . /message-api

# Install app dependencies
# A wildcard is used to ensure both package.json AND package-lock.json are copied
# where available (npm@5+)
COPY package*.json ./

# If you are building your code for production
RUN npm install --only=production

# 揭露到外部的port 此時也可以不寫 在啟動時指定
EXPOSE 8080

ENTRYPOINT [ "node",  "index.js" ]
CMD [ "release" ]
